# Generated by Django 5.1.6 on 2025-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
