# Generated by Django 5.1.6 on 2025-03-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_department_department_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='num_employees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
